# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TestProj' do

  use_frameworks!

  pod 'SwiftLint'

  target 'TestProjTests' do
  	inherit! :search_paths
    pod 'SwiftLint'
  end

end
